//
// File generated by HDevelop for HALCON/.NET (C#) Version 20.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // External procedures 
  // Chapter: Develop
  // Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
  public void dev_update_off ()
  {

    // Initialize local and output iconic variables 
    //This procedure sets different update settings to 'off'.
    //This is useful to get the best performance and reduce overhead.
    //
    // dev_update_pc(...); only in hdevelop
    // dev_update_var(...); only in hdevelop
    // dev_update_window(...); only in hdevelop


    return;
  }

  // Chapter: Graphics / Text
  // Short Description: This procedure writes one or multiple text messages. 
  public void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);
    HTuple   hv_Column_COPY_INP_TMP = new HTuple(hv_Column);
    HTuple   hv_CoordSystem_COPY_INP_TMP = new HTuple(hv_CoordSystem);
    HTuple   hv_Row_COPY_INP_TMP = new HTuple(hv_Row);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure displays text in a graphics window.
      //
      //Input parameters:
      //WindowHandle: The WindowHandle of the graphics window, where
      //   the message should be displayed.
      //String: A tuple of strings containing the text messages to be displayed.
      //CoordSystem: If set to 'window', the text position is given
      //   with respect to the window coordinate system.
      //   If set to 'image', image coordinates are used.
      //   (This may be useful in zoomed images.)
      //Row: The row coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Column: The column coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Color: defines the color of the text as string.
      //   If set to [] or '' the currently set color is used.
      //   If a tuple of strings is passed, the colors are used cyclically
      //   for every text position defined by Row and Column,
      //   or every new text line in case of |Row| == |Column| == 1.
      //Box: A tuple controlling a possible box surrounding the text.
      //   Its entries:
      //   - Box[0]: Controls the box and its color. Possible values:
      //     -- 'true' (Default): An orange box is displayed.
      //     -- 'false': No box is displayed.
      //     -- color string: A box is displayed in the given color, e.g., 'white', '#FF00CC'.
      //   - Box[1] (Optional): Controls the shadow of the box. Possible values:
      //     -- 'true' (Default): A shadow is displayed in
      //               darker orange if Box[0] is not a color and in 'white' otherwise.
      //     -- 'false': No shadow is displayed.
      //     -- color string: A shadow is displayed in the given color, e.g., 'white', '#FF00CC'.
      //
      //It is possible to display multiple text strings in a single call.
      //In this case, some restrictions apply on the
      //parameters String, Row, and Column:
      //They can only have either 1 entry or n entries.
      //Behavior in the different cases:
      //   - Multiple text positions are specified, i.e.,
      //       - |Row| == n, |Column| == n
      //       - |Row| == n, |Column| == 1
      //       - |Row| == 1, |Column| == n
      //     In this case we distinguish:
      //       - |String| == n: Each element of String is displayed
      //                        at the corresponding position.
      //       - |String| == 1: String is displayed n times
      //                        at the corresponding positions.
      //   - Exactly one text position is specified,
      //      i.e., |Row| == |Column| == 1:
      //      Each element of String is display in a new textline.
      //
      //
      //Convert the parameters for disp_text.
      if ((int)((new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(new HTuple())))) != 0)
      {

        hv_Color_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP.Dispose();
        hv_GenParamName.Dispose();
        hv_GenParamValue.Dispose();

        return;
      }
      if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Row_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP = 12;
      }
      if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Column_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP = 12;
      }
      //
      //Convert the parameter Box to generic parameters.
      hv_GenParamName.Dispose();
      hv_GenParamName = new HTuple();
      hv_GenParamValue.Dispose();
      hv_GenParamValue = new HTuple();
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
        {
          //Display no box
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(0));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
        {
          //Display no shadow.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a shadow color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(1));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      //Restore default CoordSystem behavior.
      if ((int)(new HTuple(hv_CoordSystem_COPY_INP_TMP.TupleNotEqual("window"))) != 0)
      {
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP = "image";
      }
      //
      if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        //disp_text does not accept an empty string for Color.
        hv_Color_COPY_INP_TMP.Dispose();
        hv_Color_COPY_INP_TMP = new HTuple();
      }
      //
      HOperatorSet.DispText(hv_WindowHandle, hv_String, hv_CoordSystem_COPY_INP_TMP, 
          hv_Row_COPY_INP_TMP, hv_Column_COPY_INP_TMP, hv_Color_COPY_INP_TMP, hv_GenParamName, 
          hv_GenParamValue);

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      throw HDevExpDefaultException;
    }
  }

  public void selectMaxLine (HObject ho_Contours, out HObject ho_MaxLengthContour)
  {



    // Local iconic variables 

    HObject ho_ObjectSelected=null;

    // Local control variables 

    HTuple hv_Number = new HTuple(), hv_Max_Length = new HTuple();
    HTuple hv_Max_Index = new HTuple(), hv_i = new HTuple();
    HTuple hv_Length = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_MaxLengthContour);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelected);
    try
    {
      hv_Number.Dispose();
      HOperatorSet.CountObj(ho_Contours, out hv_Number);
      hv_Max_Length.Dispose();
      hv_Max_Length = 0;
      hv_Max_Index.Dispose();
      hv_Max_Index = 0;
      //遍历每个轮廓的长度
      HTuple end_val4 = hv_Number;
      HTuple step_val4 = 1;
      for (hv_i=1; hv_i.Continue(end_val4, step_val4); hv_i = hv_i.TupleAdd(step_val4))
      {
        //选择轮廓
        ho_ObjectSelected.Dispose();
        HOperatorSet.SelectObj(ho_Contours, out ho_ObjectSelected, hv_i);
        //求轮廓长度
        hv_Length.Dispose();
        HOperatorSet.LengthXld(ho_ObjectSelected, out hv_Length);
        //保存最长轮廓的长度和索引
        if ((int)(new HTuple(hv_Max_Length.TupleLess(hv_Length))) != 0)
        {
          hv_Max_Length.Dispose();
          hv_Max_Length = new HTuple(hv_Length);
          hv_Max_Index.Dispose();
          hv_Max_Index = new HTuple(hv_i);
        }
      }
      //选择最长轮廓
      ho_MaxLengthContour.Dispose();
      HOperatorSet.SelectObj(ho_Contours, out ho_MaxLengthContour, hv_Max_Index);
      ho_ObjectSelected.Dispose();

      hv_Number.Dispose();
      hv_Max_Length.Dispose();
      hv_Max_Index.Dispose();
      hv_i.Dispose();
      hv_Length.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_ObjectSelected.Dispose();

      hv_Number.Dispose();
      hv_Max_Length.Dispose();
      hv_Max_Index.Dispose();
      hv_i.Dispose();
      hv_Length.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Local procedures 
  public void ConnectorBuckle (HObject ho_Image, HObject ho_ROI, out HObject ho_ShowRegion, 
      out HObject ho_OutImage, out HTuple hv_result)
  {



    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImageMean=null, ho_ImageReduced=null;
    HObject ho_Region=null, ho_RegionClosing=null, ho_ConnectedRegions1=null;
    HObject ho_SelectedRegions1=null, ho_SortedRegions=null;
    HObject ho_ObjectSelected=null, ho_Rectangle=null, ho_ImageReduced1=null;
    HObject ho_Region2=null, ho_ConnectedRegions=null, ho_SelectedRegions=null;
    HObject ho_RegionUnion=null, ho_RegionClosing1=null, ho_ConnectedRegions2=null;
    HObject ho_SelectedRegions4=null;

    // Local control variables 

    HTuple hv_Distances = new HTuple(), hv_Mean = new HTuple();
    HTuple hv_Deviation = new HTuple(), hv_Row1 = new HTuple();
    HTuple hv_Column1 = new HTuple(), hv_Row2 = new HTuple();
    HTuple hv_Column2 = new HTuple(), hv_Number1 = new HTuple();
    HTuple hv_Exception = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ShowRegion);
    HOperatorSet.GenEmptyObj(out ho_OutImage);
    HOperatorSet.GenEmptyObj(out ho_ImageMean);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_RegionClosing);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions1);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions1);
    HOperatorSet.GenEmptyObj(out ho_SortedRegions);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelected);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced1);
    HOperatorSet.GenEmptyObj(out ho_Region2);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionUnion);
    HOperatorSet.GenEmptyObj(out ho_RegionClosing1);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions2);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions4);
    hv_result = new HTuple();
    try
    {
      try
      {
        hv_result.Dispose();
        hv_result = 0;
        hv_Distances.Dispose();
        hv_Distances = new HTuple();
        ho_ShowRegion.Dispose();
        HOperatorSet.GenEmptyObj(out ho_ShowRegion);

        ho_ImageMean.Dispose();
        HOperatorSet.MeanImage(ho_Image, out ho_ImageMean, 9, 9);
        ho_ImageReduced.Dispose();
        HOperatorSet.ReduceDomain(ho_ImageMean, ho_ROI, out ho_ImageReduced);
        hv_Mean.Dispose();hv_Deviation.Dispose();
        HOperatorSet.Intensity(ho_ROI, ho_ImageReduced, out hv_Mean, out hv_Deviation);
        ho_Region.Dispose();
        HOperatorSet.Threshold(ho_ImageReduced, out ho_Region, 220, 255);
        ho_RegionClosing.Dispose();
        HOperatorSet.ClosingRectangle1(ho_Region, out ho_RegionClosing, 10, 50);
        ho_ConnectedRegions1.Dispose();
        HOperatorSet.Connection(ho_RegionClosing, out ho_ConnectedRegions1);
        ho_SelectedRegions1.Dispose();
        HOperatorSet.SelectShape(ho_ConnectedRegions1, out ho_SelectedRegions1, (new HTuple("area")).TupleConcat(
            "height"), "and", (new HTuple(20000)).TupleConcat(1000), (new HTuple(999999)).TupleConcat(
            9999));
        ho_SortedRegions.Dispose();
        HOperatorSet.SortRegion(ho_SelectedRegions1, out ho_SortedRegions, "first_point", 
            "false", "column");
        ho_ObjectSelected.Dispose();
        HOperatorSet.SelectObj(ho_SortedRegions, out ho_ObjectSelected, 1);
        hv_Row1.Dispose();hv_Column1.Dispose();hv_Row2.Dispose();hv_Column2.Dispose();
        HOperatorSet.SmallestRectangle1(ho_ObjectSelected, out hv_Row1, out hv_Column1, 
            out hv_Row2, out hv_Column2);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        ho_Rectangle.Dispose();
        HOperatorSet.GenRectangle1(out ho_Rectangle, hv_Row1, hv_Column1-300, hv_Row2, 
            hv_Column1-180);
        }
        {
        HObject ExpTmpOutVar_0;
        HOperatorSet.ConcatObj(ho_ShowRegion, ho_Rectangle, out ExpTmpOutVar_0);
        ho_ShowRegion.Dispose();
        ho_ShowRegion = ExpTmpOutVar_0;
        }
        ho_ImageReduced1.Dispose();
        HOperatorSet.ReduceDomain(ho_ImageReduced, ho_Rectangle, out ho_ImageReduced1
            );
        ho_Region2.Dispose();
        HOperatorSet.Threshold(ho_ImageReduced1, out ho_Region2, 220, 255);
        ho_ConnectedRegions.Dispose();
        HOperatorSet.Connection(ho_Region2, out ho_ConnectedRegions);
        ho_SelectedRegions.Dispose();
        HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
            "and", 50, 9999999);
        ho_RegionUnion.Dispose();
        HOperatorSet.Union1(ho_SelectedRegions, out ho_RegionUnion);
        ho_RegionClosing1.Dispose();
        HOperatorSet.ClosingRectangle1(ho_RegionUnion, out ho_RegionClosing1, 20, 
            80);
        ho_ConnectedRegions2.Dispose();
        HOperatorSet.Connection(ho_RegionClosing1, out ho_ConnectedRegions2);
        ho_SelectedRegions4.Dispose();
        HOperatorSet.SelectShape(ho_ConnectedRegions2, out ho_SelectedRegions4, (new HTuple("area")).TupleConcat(
            "width"), "and", (new HTuple(80000)).TupleConcat(80), (new HTuple(999999)).TupleConcat(
            150));

        hv_Number1.Dispose();
        HOperatorSet.CountObj(ho_SelectedRegions4, out hv_Number1);
        if ((int)(new HTuple(hv_Number1.TupleEqual(0))) != 0)
        {
          hv_result.Dispose();
          hv_result = 1;
        }
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        hv_Distances.Dispose();
        hv_Distances = new HTuple();
        hv_Distances[0] = 0;
        hv_Distances[1] = 0;
        hv_result.Dispose();
        hv_result = 1;
      }
      ho_ImageMean.Dispose();
      ho_ImageReduced.Dispose();
      ho_Region.Dispose();
      ho_RegionClosing.Dispose();
      ho_ConnectedRegions1.Dispose();
      ho_SelectedRegions1.Dispose();
      ho_SortedRegions.Dispose();
      ho_ObjectSelected.Dispose();
      ho_Rectangle.Dispose();
      ho_ImageReduced1.Dispose();
      ho_Region2.Dispose();
      ho_ConnectedRegions.Dispose();
      ho_SelectedRegions.Dispose();
      ho_RegionUnion.Dispose();
      ho_RegionClosing1.Dispose();
      ho_ConnectedRegions2.Dispose();
      ho_SelectedRegions4.Dispose();

      hv_Distances.Dispose();
      hv_Mean.Dispose();
      hv_Deviation.Dispose();
      hv_Row1.Dispose();
      hv_Column1.Dispose();
      hv_Row2.Dispose();
      hv_Column2.Dispose();
      hv_Number1.Dispose();
      hv_Exception.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_ImageMean.Dispose();
      ho_ImageReduced.Dispose();
      ho_Region.Dispose();
      ho_RegionClosing.Dispose();
      ho_ConnectedRegions1.Dispose();
      ho_SelectedRegions1.Dispose();
      ho_SortedRegions.Dispose();
      ho_ObjectSelected.Dispose();
      ho_Rectangle.Dispose();
      ho_ImageReduced1.Dispose();
      ho_Region2.Dispose();
      ho_ConnectedRegions.Dispose();
      ho_SelectedRegions.Dispose();
      ho_RegionUnion.Dispose();
      ho_RegionClosing1.Dispose();
      ho_ConnectedRegions2.Dispose();
      ho_SelectedRegions4.Dispose();

      hv_Distances.Dispose();
      hv_Mean.Dispose();
      hv_Deviation.Dispose();
      hv_Row1.Dispose();
      hv_Column1.Dispose();
      hv_Row2.Dispose();
      hv_Column2.Dispose();
      hv_Number1.Dispose();
      hv_Exception.Dispose();

      throw HDevExpDefaultException;
    }
  }

  public void FindLine (HObject ho_Image, out HObject ho_RegionLines, HTuple hv_position, 
      HTuple hv_minLength, out HTuple hv_RowBegin, out HTuple hv_ColBegin, out HTuple hv_RowEnd, 
      out HTuple hv_ColEnd)
  {




    // Local iconic variables 

    HObject ho_Edges=null, ho_MaxLengthContour=null;
    HObject ho_ContoursSplit=null, ho_SelectedXLD=null, ho_UnionContours=null;
    HObject ho_MaxLengthContour1=null;

    // Local control variables 

    HTuple hv_Nr = new HTuple(), hv_Nc = new HTuple();
    HTuple hv_Dist = new HTuple(), hv_Exception = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_RegionLines);
    HOperatorSet.GenEmptyObj(out ho_Edges);
    HOperatorSet.GenEmptyObj(out ho_MaxLengthContour);
    HOperatorSet.GenEmptyObj(out ho_ContoursSplit);
    HOperatorSet.GenEmptyObj(out ho_SelectedXLD);
    HOperatorSet.GenEmptyObj(out ho_UnionContours);
    HOperatorSet.GenEmptyObj(out ho_MaxLengthContour1);
    hv_RowBegin = new HTuple();
    hv_ColBegin = new HTuple();
    hv_RowEnd = new HTuple();
    hv_ColEnd = new HTuple();
    try
    {
      try
      {
        //emphasize (Image, ImageEmphasize, 7, 7, 1)

        ho_Edges.Dispose();
        HOperatorSet.EdgesSubPix(ho_Image, out ho_Edges, "canny", 2, 20, 40);
        ho_MaxLengthContour.Dispose();
        selectMaxLine(ho_Edges, out ho_MaxLengthContour);
        ho_ContoursSplit.Dispose();
        HOperatorSet.SegmentContoursXld(ho_MaxLengthContour, out ho_ContoursSplit, 
            "lines_circles", 1, 4, 1);
        if ((int)(new HTuple(hv_position.TupleEqual("vertical"))) != 0)
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          ho_SelectedXLD.Dispose();
          HOperatorSet.SelectShapeXld(ho_ContoursSplit, out ho_SelectedXLD, (new HTuple("phi_points")).TupleConcat(
              "height"), "and", (new HTuple(1.4)).TupleConcat(hv_minLength), (new HTuple(1.6)).TupleConcat(
              9999));
          }
        }
        else
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          ho_SelectedXLD.Dispose();
          HOperatorSet.SelectShapeXld(ho_ContoursSplit, out ho_SelectedXLD, (new HTuple("phi_points")).TupleConcat(
              "width"), "and", (new HTuple(-0.2)).TupleConcat(hv_minLength), (new HTuple(0.2)).TupleConcat(
              9999));
          }
        }
        ho_UnionContours.Dispose();
        HOperatorSet.UnionCollinearContoursXld(ho_SelectedXLD, out ho_UnionContours, 
            100, 1, 2, 0.1, "attr_keep");
        //union_adjacent_contours_xld (SelectedXLD, UnionContours, 100, 1, 'attr_keep')
        ho_MaxLengthContour1.Dispose();
        selectMaxLine(ho_UnionContours, out ho_MaxLengthContour1);
        hv_RowBegin.Dispose();hv_ColBegin.Dispose();hv_RowEnd.Dispose();hv_ColEnd.Dispose();hv_Nr.Dispose();hv_Nc.Dispose();hv_Dist.Dispose();
        HOperatorSet.FitLineContourXld(ho_MaxLengthContour1, "tukey", -1, 0, 5, 2, 
            out hv_RowBegin, out hv_ColBegin, out hv_RowEnd, out hv_ColEnd, out hv_Nr, 
            out hv_Nc, out hv_Dist);
        ho_RegionLines.Dispose();
        HOperatorSet.GenRegionLine(out ho_RegionLines, hv_RowBegin, hv_ColBegin, 
            hv_RowEnd, hv_ColEnd);
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
      }
      ho_Edges.Dispose();
      ho_MaxLengthContour.Dispose();
      ho_ContoursSplit.Dispose();
      ho_SelectedXLD.Dispose();
      ho_UnionContours.Dispose();
      ho_MaxLengthContour1.Dispose();

      hv_Nr.Dispose();
      hv_Nc.Dispose();
      hv_Dist.Dispose();
      hv_Exception.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Edges.Dispose();
      ho_MaxLengthContour.Dispose();
      ho_ContoursSplit.Dispose();
      ho_SelectedXLD.Dispose();
      ho_UnionContours.Dispose();
      ho_MaxLengthContour1.Dispose();

      hv_Nr.Dispose();
      hv_Nc.Dispose();
      hv_Dist.Dispose();
      hv_Exception.Dispose();

      throw HDevExpDefaultException;
    }
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_Image=null, ho_ROI_0=null, ho_ShowRegion=null;
    HObject ho_OutImage=null;

    // Local control variables 

    HTuple hv_ImageFiles = new HTuple(), hv_Index = new HTuple();
    HTuple hv_result = new HTuple(), hv_WindowHandle = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_ROI_0);
    HOperatorSet.GenEmptyObj(out ho_ShowRegion);
    HOperatorSet.GenEmptyObj(out ho_OutImage);
    try
    {
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
      }
      dev_update_off();
      //read_image (Image, 'E:/power flex/Power flex&Connector buckle2.bmp')
      //Image Acquisition 01: Code generated by Image Acquisition 01
      hv_ImageFiles.Dispose();
      HOperatorSet.ListFiles("C:/Users/LEO1990/Downloads/starfire11-18(MLB)", (new HTuple("files")).TupleConcat(
          "follow_links"), out hv_ImageFiles);
      {
      HTuple ExpTmpOutVar_0;
      HOperatorSet.TupleRegexpSelect(hv_ImageFiles, (new HTuple("\\.(tif|tiff|gif|bmp|jpg|jpeg|jp2|png|pcx|pgm|ppm|pbm|xwd|ima|hobj)$")).TupleConcat(
          "ignore_case"), out ExpTmpOutVar_0);
      hv_ImageFiles.Dispose();
      hv_ImageFiles = ExpTmpOutVar_0;
      }
      for (hv_Index=0; (int)hv_Index<=(int)((new HTuple(hv_ImageFiles.TupleLength()
          ))-1); hv_Index = (int)hv_Index + 1)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        ho_Image.Dispose();
        HOperatorSet.ReadImage(out ho_Image, hv_ImageFiles.TupleSelect(hv_Index));
        }
        //read_image (Image, 'C:/Users/Administrator.DESKTOP-0F1Q0E8/Desktop/MLB flex&Connector buckle.bmp')
        {
        HObject ExpTmpOutVar_0;
        HOperatorSet.RotateImage(ho_Image, out ExpTmpOutVar_0, 90, "constant");
        ho_Image.Dispose();
        ho_Image = ExpTmpOutVar_0;
        }
        //rotate_image (Image, Image, 90, 'constant')
        //gen_rectangle1 (MLB, 213.645, 1357.53, 2009.14, 1585.2)
        //Image Acquisition 01: Do something

        ho_ROI_0.Dispose();
        HOperatorSet.GenRectangle1(out ho_ROI_0, 245.096, 641.51, 2204.87, 1440.06);

        ho_ShowRegion.Dispose();ho_OutImage.Dispose();hv_result.Dispose();
        ConnectorBuckle(ho_Image, ho_ROI_0, out ho_ShowRegion, out ho_OutImage, out hv_result);
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.ClearWindow(HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_ROI_0, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "red");
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_ShowRegion, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          hv_WindowHandle = HDevWindowStack.GetActive();
        }
        if ((int)(new HTuple(hv_result.TupleEqual(1))) != 0)
        {
          HOperatorSet.SetFont(hv_WindowHandle, "Times New Roman-55");
          disp_message(hv_WindowHandle, "NG", "window", 12, 12, "black", "true");
          // stop(...); only in hdevelop
        }
        else
        {
          HOperatorSet.SetFont(hv_WindowHandle, "Times New Roman-55");
          disp_message(hv_WindowHandle, "OK", "window", 12, 12, "black", "true");
          //stop ()
        }
        //dump_window (WindowHandle, 'png', Index+ '.bmp')
        //*     endif
        // stop(...); only in hdevelop
      }








    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Image.Dispose();
      ho_ROI_0.Dispose();
      ho_ShowRegion.Dispose();
      ho_OutImage.Dispose();

      hv_ImageFiles.Dispose();
      hv_Index.Dispose();
      hv_result.Dispose();
      hv_WindowHandle.Dispose();

      throw HDevExpDefaultException;
    }
    ho_Image.Dispose();
    ho_ROI_0.Dispose();
    ho_ShowRegion.Dispose();
    ho_OutImage.Dispose();

    hv_ImageFiles.Dispose();
    hv_Index.Dispose();
    hv_result.Dispose();
    hv_WindowHandle.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

